export ZSH="$HOME/.config/oh-my-zsh"
export ZSH_CUSTOM="${ZSH_CUSTOM:-$ZSH/custom}"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting web-search)
source $ZSH/oh-my-zsh.sh

eval "$(oh-my-posh init zsh --config $HOME/.config/oh-my-posh/themes/spaceship.omp.json)"

alias vim="nvim"
# alias ls="eza --icons --group-directories-first"
# alias ll="eza --icons -l --group-directories-first"

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin"
export PATH="$HOME/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

eval "$(zoxide init --cmd cd zsh)"
